#!/usr/bin/env bash
# publish-4-hub.sh — publish the standalone 4-hub mirror from this monorepo.
#
# 4-hub (github.com/dp-web4/4-hub) is a READ-ONLY mirror containing hub/ and
# web4-core/ with monorepo layout preserved, so hub's relative path dependency
# (hub/Cargo.toml: web4-core = { path = "../web4-core" }) resolves and a fresh
# clone builds with plain `cargo build`. Development happens HERE, in web4 —
# run this script after hub-relevant changes land to refresh the mirror.
#
# Mechanism: fresh clone -> git filter-repo (history rewritten to the kept
# paths) -> add a mirror-only root README -> force-push. The mirror is fully
# derived; every run rebuilds it deterministically. Requires git-filter-repo
# (pip install git-filter-repo) and push access to dp-web4/4-hub.
set -euo pipefail

MONOREPO="$(cd "$(dirname "$0")/.." && pwd)"
MIRROR_REMOTE="git@github.com:dp-web4/4-hub.git"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

echo "[4-hub] fresh clone of monorepo..."
git clone --no-local -q "$MONOREPO" "$WORK/mirror"
cd "$WORK/mirror"

echo "[4-hub] filtering history to hub/ + web4-core/ (+ root license/patents)..."
git filter-repo --quiet \
  --path hub \
  --path web4-core \
  --path LICENSE \
  --path PATENTS.md

echo "[4-hub] adding mirror root README..."
cat > README.md << 'EOF'
# 4-hub — Web4 Community Hub (standalone mirror)

A single-binary Rust daemon (~6 MB) that turns a community into a sovereign
Web4 society: 7 roles, a signed machine-readable founding law, an append-only
witnessed ledger, sealed member<->hub channels, and a multi-surface API
(MCP `/tools/*`, REST `/v1`, admin web GUI).

**Start here: [`hub/README.md`](hub/README.md).**

## Layout

| Path | What it is |
|---|---|
| [`hub/`](hub/) | The hub itself: `hub-daemon`, `hub-lib`, `hub-plugin`, docs, examples |
| [`web4-core/`](web4-core/) | The Web4 core library the hub builds on (MIT-licensed) |

## Build

```bash
cd hub && cargo build --release
```

The monorepo layout is preserved so `hub/`'s relative path dependency on
`../web4-core` resolves in this standalone clone.

## Where development happens

This repository is a **read-only mirror**, published from the
[`hub/`](https://github.com/dp-web4/web4/tree/main/hub) directory of the
[dp-web4/web4](https://github.com/dp-web4/web4) monorepo by
`scripts/publish-4-hub.sh`. History here is the filtered history of those
paths. **File issues and PRs against
[dp-web4/web4](https://github.com/dp-web4/web4).**

## License

Root [`LICENSE`](LICENSE) (AGPL-3.0-or-later) covers `hub/`;
[`web4-core/`](web4-core/) carries its own MIT license.
EOF
git add README.md
git -c user.name="4-hub mirror" -c user.email="noreply@metalinxx.io" \
  commit -q -m "mirror: root README (generated by scripts/publish-4-hub.sh)"

echo "[4-hub] force-pushing mirror..."
git push --force -q "$MIRROR_REMOTE" HEAD:main

echo "[4-hub] done: https://github.com/dp-web4/4-hub"
